<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="0" ignored="0" total="1" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="21753" started-at="2020-06-14T12:50:25Z" finished-at="2020-06-14T12:50:47Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="21753" started-at="2020-06-14T12:50:25Z" finished-at="2020-06-14T12:50:47Z">
      <class name="tests.sanity.Sanity_001_Add_Admin_User">
        <test-method status="PASS" signature="setUp()[pri:0, instance:tests.sanity.Sanity_001_Add_Admin_User@667a738]" name="setUp" is-config="true" duration-ms="9395" started-at="2020-06-14T12:50:25Z" finished-at="2020-06-14T12:50:35Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="Sanity_001_Add_Admin_User_Test()[pri:0, instance:tests.sanity.Sanity_001_Add_Admin_User@667a738]" name="Sanity_001_Add_Admin_User_Test" duration-ms="10774" started-at="2020-06-14T12:50:35Z" finished-at="2020-06-14T12:50:45Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Sanity_001_Add_Admin_User_Test -->
        <test-method status="FAIL" signature="tearDown()[pri:0, instance:tests.sanity.Sanity_001_Add_Admin_User@667a738]" name="tearDown" is-config="true" duration-ms="1557" started-at="2020-06-14T12:50:45Z" finished-at="2020-06-14T12:50:47Z">
          <exception class="java.lang.AssertionError">
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:86)
at org.junit.Assert.assertTrue(Assert.java:41)
at org.junit.Assert.assertTrue(Assert.java:52)
at common.Login.tearDown(Login.java:30)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:458)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- tests.sanity.Sanity_001_Add_Admin_User -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
